[workspace]
name = "xcub-moveit2"
version = "0.1.0"
description = "Add a short description here"
authors = ["martina.gloria@iit.it"]
channels = ["robostack-jazzy", "conda-forge", "robotology"]
# Your project can support multiple platforms, the current platform will be automatically added.
platforms = ["linux-64"]

[tasks]

[dependencies]
ros-jazzy-ros-core = "*"
ros-jazzy-desktop-full = "*"
ros-jazzy-moveit-ros-planning-interface = "*"
ros-jazzy-control-msgs = "*"
ros-jazzy-moveit-ros-visualization = "*"
ros-jazzy-rviz2 = "*"
ros-jazzy-ros-gz-interfaces = "*"
ros-jazzy-moveit-visual-tools = "*"
ros-jazzy-controller-manager = "*"
ros-jazzy-moveit-configs-utils = "*"
ros-jazzy-ros-gz-sim = "*"

ergocub-software = "*"
gz-sim-yarp-plugins = ">=0.5.0,<0.6"
libgz-sim-yarp-plugins = ">=0.5.0,<0.6"
