[workspace]
name = "xcub-moveit2"
version = "0.1.0"
description = "Add a short description here"
authors = ["User Name <user.name@email.url>"]
channels = ["robostack-jazzy", "conda-forge", "robotology"]
# Your project can support multiple platforms, the current platform will be automatically added.
platforms = ["linux-64"]

[tasks]

[dependencies]
ros-jazzy-desktop = ">=0.11.0,<0.12"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = "<=58.2.0"
python = ">=3.10"
pip = "*"
ros-jazzy-moveit = ">=2.12.1,<3"
ros-jazzy-ros-gz-sim = ">=1.0.7,<2"
ergocub-software = ">=0.7.9,<0.8"
icub-models = ">=3.1.0,<4"
ros-jazzy-rviz-visual-tools = ">=4.1.4,<5"
ros-jazzy-ros-gz-interfaces = ">=1.0.7,<2"
protobuf = ">=5.28.3,<6"

[activation]
scripts = ["install/setup.sh"]
